### ISSUE TITLE
[BUG] qq闪退

### ISSUE THREAD

**Issue by rhjdvsgsgks** [solohsu/EdXposed#24]
**什么情况/What happened?**

qq闪退

**Xposed模块列表/Xposed Module List**

qx

**Magisk模块列表/Magisk Module List**

Riru core 和 edxposed

**EdXposed及Riru版本/Versions of EdXposed and Riru**

EdXposed:0295b

Riru:v10

**相关Logcat/Logcat**

java.lang.IncompatibleClassChangeError: The method 'void com.tencent.common.app.BaseApplicationImpl.onCreate()' was expected to be of type static but instead was found to be of type virtual (declaration of 'EdHooker2' appears in /data/user_de/0/com.tencent.mobileqq/cache/edhookers/com.tencent.mobileqq/Generated_1554686410.jar)
	at EdHooker2.hook(Unknown Source:101)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(QFixApplication.java:30)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
	at com.elderdrivers.riru.xposed.c.b.a.hook(Unknown Source:229)
	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by solohsu** [comment]
https://github.com/solohsu/EdXpManager/releases
刷入 0297，安装 EdXp Manager最新版，点击 手机QQ，点击清除，执行完后再点击编译speed，
然后兼容模式页面，勾选手机QQ，启动手机QQ，耐心等待。
